#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
n=1
while (( n <= 10 ))
do

        if [ "$n" = "9" ]
        then
                echo "Hi"
                ((n=n+1))
        else
                echo "Holberton School"
                ((n=n+1))
        fi
done
