#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
n=1
while (( n <= 20 ))
do
echo "$n"
case $n in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    ((n=n+1))
done
